# Generated by Django 5.1.2 on 2024-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('app_name', models.CharField(max_length=64, verbose_name='程序名称')),
                ('package_name', models.CharField(default='package', max_length=64, verbose_name='程序包名称')),
                ('permissions', models.CharField(default='no permissions', max_length=1000, verbose_name='程序权限')),
                ('registered_activities', models.CharField(default='no registered_activities', max_length=1000, verbose_name='程序注册活动')),
                ('all_class_names', models.CharField(default='no class', max_length=1000, verbose_name='程序类名')),
                ('defined_strings', models.CharField(default='no defined_strings', max_length=1000, verbose_name='程序定义字符串')),
                ('defined_methods', models.CharField(default='no defined_methods', max_length=1000, verbose_name='程序定义方法')),
                ('services', models.CharField(default='no service', max_length=1000, verbose_name='程序服务')),
                ('api_calls', models.CharField(default='no api', max_length=1000, verbose_name='程序api')),
                ('base_info', models.CharField(default='no base_info', max_length=1000, verbose_name='程序基础信息')),
                ('locations', models.CharField(default='no location', max_length=1000, verbose_name='位置')),
            ],
        ),
    ]
