# Generated by Django 5.1.2 on 2024-10-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_ocrimage_ocruser_delete_appinfo_ocrimage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrimage',
            name='image_path',
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='image',
            field=models.ImageField(default='test.png', upload_to='images/'),
        ),
    ]
